version: '3.8'

services:
  chatbot:
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
    # No container_name - let Coolify manage it
    # No ports - Coolify's reverse proxy handles external access
    expose:
      - "80"  # Internal port for nginx
    environment:
      - NODE_ENV=production
      - REACT_APP_N8N_WEBHOOK_URL=${REACT_APP_N8N_WEBHOOK_URL}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"