version: '3.8'

services:
  chatbot:
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
    container_name: chatbot-prod
    # Coolify handles port mapping via reverse proxy
    # No ports mapping needed here
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - REACT_APP_N8N_WEBHOOK_URL=${REACT_APP_N8N_WEBHOOK_URL}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - chatbot-network

  # Optional: Add nginx as reverse proxy with SSL termination
  # nginx:
  #   image: nginx:alpine
  #   container_name: chatbot-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - chatbot
  #   restart: unless-stopped
  #   networks:
  #     - chatbot-network

networks:
  chatbot-network:
    driver: bridge
    name: chatbot-prod-network